{{- if and .Values.chaosMesh.enabled (and .Values.chaosMesh.stressChaos .Values.chaosMesh.stressChaos.enabled) }}
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: {{ include "kairoscloud-chart.fullname" . }}-stress-chaos
  labels:
    {{- include "kairoscloud-chart.labels" . | nindent 4 }}
  {{- with .Values.chaosMesh.stressChaos.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  mode: {{ .Values.chaosMesh.stressChaos.mode | default "one" }}
  selector:
    {{- if .Values.chaosMesh.stressChaos.selector }}
    {{- toYaml .Values.chaosMesh.stressChaos.selector | nindent 4 }}
    {{- else }}
    namespaces:
      - {{ .Release.Namespace }}
    labelSelectors:
      app.kubernetes.io/name: {{ include "kairoscloud-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
    {{- end }}
  duration: {{ .Values.chaosMesh.stressChaos.duration | default "30s" }}
  {{- if .Values.chaosMesh.stressChaos.stressors }}
  stressors:
    {{- toYaml .Values.chaosMesh.stressChaos.stressors | nindent 4 }}
  {{- end }}
  {{- if .Values.chaosMesh.stressChaos.containerName }}
  containerName: {{ .Values.chaosMesh.stressChaos.containerName }}
  {{- end }}
  {{- if .Values.chaosMesh.stressChaos.percent }}
  percent: {{ .Values.chaosMesh.stressChaos.percent }}
  {{- end }}
{{- end }}
