{{- if .Values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kairoscloud-chart.fullname" . }}-clusterrole
  labels:
    {{- include "kairoscloud-chart.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end }}
