{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kairoscloud-chart.fullname" . }}-job
  labels:
    {{- include "kairoscloud-chart.labels" . | nindent 4 }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.job.backoffLimit }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
  {{- if .Values.job.completions }}
  completions: {{ .Values.job.completions }}
  {{- end }}
  {{- if .Values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  {{- end }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "kairoscloud-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kairoscloud-chart.serviceAccountName" . }}
      restartPolicy: {{ .Values.job.restartPolicy | default "Never" }}
      {{- if .Values.job.securityContext }}
      securityContext:
        {{- toYaml .Values.job.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-job
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy | default .Values.deployment.image.pullPolicy }}
          {{- if .Values.job.command }}
          command:
            {{- toYaml .Values.job.command | nindent 12 }}
          {{- end }}
          {{- if .Values.job.args }}
          args:
            {{- toYaml .Values.job.args | nindent 12 }}
          {{- end }}
          {{- if .Values.job.env }}
          env:
            {{- toYaml .Values.job.env | nindent 12 }}
          {{- end }}
          {{- if .Values.job.resources }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.job.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.job.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.job.volumes }}
      volumes:
        {{- toYaml .Values.job.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
