{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kairoscloud-chart.fullname" . }}
  labels:
    {{- include "kairoscloud-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kairoscloud-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - from:
        {{- if .Values.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.ingress.ipBlocks }}
        {{- range .Values.networkPolicy.ingress.ipBlocks }}
        - ipBlock:
            cidr: {{ .cidr }}
            {{- if .except }}
            except:
              {{- toYaml .except | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.ingress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- else }}
    - {}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress.enabled }}
    - to:
        {{- if .Values.networkPolicy.egress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.egress.namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.egress.podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.egress.podSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.egress.ipBlocks }}
        {{- range .Values.networkPolicy.egress.ipBlocks }}
        - ipBlock:
            cidr: {{ .cidr }}
            {{- if .except }}
            except:
              {{- toYaml .except | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.egress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- else }}
    - {}
    {{- end }}
{{- end }}
