{{- if .Values.validatingWebhookConfiguration.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kairoscloud-chart.fullname" . }}-validating-webhook
  labels:
    {{- include "kairoscloud-chart.labels" . | nindent 4 }}
  {{- with .Values.validatingWebhookConfiguration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  {{- range .Values.validatingWebhookConfiguration.webhooks }}
  - name: {{ .name }}
    {{- if .clientConfig }}
    clientConfig:
      {{- if .clientConfig.url }}
      url: {{ .clientConfig.url }}
      {{- end }}
      {{- if .clientConfig.service }}
      service:
        {{- if .clientConfig.service.name }}
        name: {{ .clientConfig.service.name }}
        {{- end }}
        {{- if .clientConfig.service.namespace }}
        namespace: {{ .clientConfig.service.namespace }}
        {{- end }}
        {{- if .clientConfig.service.path }}
        path: {{ .clientConfig.service.path }}
        {{- end }}
        {{- if .clientConfig.service.port }}
        port: {{ .clientConfig.service.port }}
        {{- end }}
      {{- end }}
      {{- if .clientConfig.caBundle }}
      caBundle: {{ .clientConfig.caBundle }}
      {{- end }}
    {{- end }}
    {{- if .rules }}
    rules:
      {{- toYaml .rules | nindent 6 }}
    {{- end }}
    {{- if .failurePolicy }}
    failurePolicy: {{ .failurePolicy }}
    {{- end }}
    {{- if .matchPolicy }}
    matchPolicy: {{ .matchPolicy }}
    {{- end }}
    {{- if .namespaceSelector }}
    namespaceSelector:
      {{- toYaml .namespaceSelector | nindent 6 }}
    {{- end }}
    {{- if .objectSelector }}
    objectSelector:
      {{- toYaml .objectSelector | nindent 6 }}
    {{- end }}
    {{- if .sideEffects }}
    sideEffects: {{ .sideEffects }}
    {{- end }}
    {{- if .timeoutSeconds }}
    timeoutSeconds: {{ .timeoutSeconds }}
    {{- end }}
    {{- if .admissionReviewVersions }}
    admissionReviewVersions:
      {{- toYaml .admissionReviewVersions | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
